global:
  scrape_interval:     5s
  #evaluation_interval: 10s

scrape_configs:
  - job_name: 'backend_1_system'
    static_configs:
      - targets: ['18.221.25.126:9100']

  - job_name: 'backend_2_system'
    static_configs:
      - targets: ['18.220.52.248:9100']

  - job_name: 'backend_3_system'
    static_configs:
      - targets: ['18.221.104.251:9100']

  - job_name: 'balancer_system'
    static_configs:
      - targets: ['3.14.129.220:9100']

  - job_name: 'dummy_service'
    static_configs:
        - targets: ['18.221.25.126:8081', '18.220.52.248:8081', '18.221.104.251:8081']
